# config.properties
# Base URL
base.url=https://www.saucedemo.com/

# Valid Credentials
username.valid=standard_user
password.valid=secret_sauce

# Invalid Credentials
username.invalid=locked_out_user
password.invalid=wrong_password

# Browser Options
browser=headless=false

